# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popular_themes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('time', models.DateTimeField(verbose_name='time comment')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('time', models.DateTimeField(verbose_name='time thumb')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(validators=[popular_themes.models.validate_date], verbose_name='date uploaded')),
                ('views', models.IntegerField(default=0)),
                ('themes', models.ManyToManyField(to='popular_themes.Theme')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='thumb',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_themes.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_themes.Video'),
        ),
    ]
